#!/bin/sh /etc/rc.common

START=65
STOP=20
USE_PROCD=1
PROG=/usr/libexec/miniui/miniui-ubus

start_service() {
	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param respawn
	procd_close_instance
}
